//
//  CoreDataManager.swift
//  TrelloProgect
//
//  Created by Maxim Panamarou on 8/6/18.
//  Copyright © 2018 Maxim Panamarou. All rights reserved.
//

import Foundation
import Alamofire
import CoreData

//////////   //TODO: create convinience init with context and board
//////////   // TODO find autogenerated constansts for keys

class CoreDataManager {
  
  static let `default` = CoreDataManager()
  
  let api  =  ServerManager.default
  
 lazy var readContext :  NSManagedObjectContext = {
    let context =  NSManagedObjectContext(concurrencyType: .mainQueueConcurrencyType)
    context.parent = persistentContainer.viewContext
    return context
  }()
  
  // TODO: use background queue
  lazy var writeContext : NSManagedObjectContext = {
    let context =  NSManagedObjectContext(concurrencyType: .mainQueueConcurrencyType)
    context.parent = persistentContainer.viewContext
    return context
  }()
  
  lazy var persistentContainer: NSPersistentContainer = {
    let container = NSPersistentContainer(name: "TrelloProgect")
    container.loadPersistentStores(completionHandler: { (_, error) in
      if let error = error as NSError? {
        fatalError("Unresolved error \(error), \(error.userInfo)")
      }
    })
    return container
  }()
  
   func saveContext () {
    if writeContext.hasChanges{
      trySave(Context: writeContext)
    }
    if readContext.hasChanges{
      trySave(Context: readContext)
    }
    if persistentContainer.viewContext.hasChanges {
      trySave(Context: persistentContainer.viewContext)
    }
  }
  
  private func trySave(Context context: NSManagedObjectContext){
    //TODO: check hasChanges here and save parent
    do {
      try context.save()
    } catch {
      let nserror = error as NSError
      fatalError("Unresolved error \(nserror), \(nserror.userInfo)")
    }
  }
  
  func putCardsId(_ cardId: String, description : String, completion : @escaping (Any?) -> Void){
    api.putCardsId(cardId, description: description) { (result) in
     
    }
    
  }
}




